default_platform(:ios)

platform :ios do
  desc "Build iOS app without code signing (macOS only)"
  lane :build_no_codesign do
    sh("cd .. && flutter build ios --release --no-codesign")
  end

  desc "Build a signed IPA and upload to TestFlight"
  lane :beta do |options|
    api_key = app_store_connect_api_key(
      key_id: ENV.fetch("ASC_KEY_ID"),
      issuer_id: ENV.fetch("ASC_ISSUER_ID"),
      key_filepath: ENV.fetch("ASC_KEY_FILEPATH"),
      in_house: false
    )

    cmd = ["cd .. && flutter build ipa --release"]
    cmd << "--build-name=#{options[:build_name]}" if options[:build_name]
    cmd << "--build-number=#{options[:build_number]}" if options[:build_number]
    sh(cmd.join(" "))

    ipa_path = Dir["../build/ios/ipa/*.ipa"].first
    UI.user_error!("No IPA found in ../build/ios/ipa") if ipa_path.nil?

    upload_to_testflight(
      api_key: api_key,
      ipa: ipa_path,
      skip_waiting_for_build_processing: true
    )
  end
end
