# Generated by Django 5.2.10 on 2026-01-08 20:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('default_target_units_per_child', models.PositiveIntegerField(default=0)),
                ('buyout_amount_per_child', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='SEK', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='core.team')),
            ],
        ),
    ]
