# Generated by Django 5.2.10 on 2026-01-08 20:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_child_guardianchildlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCampaignTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_units', models.PositiveIntegerField(blank=True, null=True)),
                ('buyout_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('has_paid_buyout', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_targets', to='core.campaign')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_targets', to='core.child')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('child', 'campaign'), name='uniq_child_campaign_target')],
            },
        ),
    ]
